### ISSUE TITLE
Error when I change the key list if DataSaver with refresh=True

### ISSUE THREAD

**Issue by jinserk** [graykode/matorage#22]
When I added attributes with DataSaver `refresh=True`, it gives an error like:
```
Traceback (most recent call last):
  File "/home/jinserk/.pyenv/versions/3.8.5/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/jinserk/.pyenv/versions/3.8.5/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/mnt/ssd2/works/kyulux/kyumlm/tddft/ann/feature.py", line 205, in <module>
    store_to_matorage(ds)
  File "/mnt/ssd2/works/kyulux/kyumlm/tddft/ann/feature.py", line 198, in store_to_matorage
    save_data_list(train_list, "train")
  File "/mnt/ssd2/works/kyulux/kyumlm/tddft/ann/feature.py", line 190, in save_data_list
    data_saver({
  File "/home/jinserk/.pyenv/versions/kyumlm/lib/python3.8/site-packages/matorage/data/saver.py", line 317, in __call__
    self._check_data_numpytype()
  File "/home/jinserk/.pyenv/versions/kyumlm/lib/python3.8/site-packages/matorage/data/saver.py", line 254, in _check_data_numpytype
    self._check_attr_name(name=name)
  File "/home/jinserk/.pyenv/versions/kyumlm/lib/python3.8/site-packages/matorage/data/saver.py", line 229, in _check_attr_name
    raise KeyError("attribute name {} is not exist!".format(name))
KeyError: 'attribute name inchikey is not exist!'
```

It seems to check the config attributes keys as well as the other params, or to reset the attributes when `refresh=True`.

**Comment by graykode** [comment]
Like the previous issue (#21), this error seems to be a problem of the `list_object` function overridden in the NAS. If that doesn't work, please ask again for me. Thanks
